<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 10-10-2018
 * Time: 09:18
 */

namespace app\components;


use Yii;
use yii\base\Component;

class MainMenu extends Component {

    const EVENT_MAINMENU_REGISTER = 'module.mainmenu.register';

    protected $items = [];

    public function init() {
        Yii::beginProfile("Main menu register event",__CLASS__);
        $this->trigger(self::EVENT_MAINMENU_REGISTER);
        Yii::endProfile("Main menu register event",__CLASS__);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function addItem($item) {
        if (!isset($item['sortOrder']))
            $item['sortOrder'] = 1000;
        $this->items[] = $item;
    }

    public function getItems() {
        $this->sortItems();
        return $this->items;
    }


    /**
     * Sorts the item attribute by sortOrder
     */
    private function sortItems() {
        usort($this->items, function ($a, $b) {
            if ($a['sortOrder'] == $b['sortOrder']) {
                return 0;
            } else
                if ($a['sortOrder'] < $b['sortOrder']) {
                    return - 1;
                } else {
                    return 1;
                }
        });
    }

}